from __future__ import annotations

from typing import Any


def _option(code: str, label: str) -> dict[str, str]:
    return {"code": code, "label": label}


SEVERITY_OPTIONS = [
    _option("minor", "Minor"),
    _option("moderate", "Moderate"),
    _option("major", "Major"),
]
SUBSTRATE_CONDITION_OPTIONS = [
    _option("sound", "Sound"),
    _option("minor-prep", "Minor Prep Needed"),
    _option("major-prep", "Major Prep Needed"),
    _option("moisture-affected", "Moisture Affected"),
]
EXISTING_CONDITION_OPTIONS = [
    _option("sound", "Sound"),
    _option("weathered", "Weathered"),
    _option("locally-damaged", "Locally Damaged"),
    _option("failed", "Failed"),
]
OPENING_CONDITION_OPTIONS = [
    _option("ready-opening", "Ready Opening"),
    _option("minor-adjustment", "Minor Adjustment"),
    _option("structural-rework", "Structural Rework"),
    _option("moisture-damaged", "Moisture Damaged"),
]
GROUND_CONDITION_OPTIONS = [
    _option("standard-soil", "Standard Soil"),
    _option("wet-soil", "Wet Soil"),
    _option("rocky-ground", "Rocky Ground"),
    _option("restricted-dig", "Restricted Dig"),
]
ACCESS_EXTERIOR_OPTIONS = [
    _option("ground-level", "Ground Level"),
    _option("ladder-access", "Ladder Access"),
    _option("scaffold-access", "Scaffold Access"),
    _option("mobile-lift", "Mobile Lift"),
    _option("rope-access", "Rope Access"),
]
ACCESS_INTERIOR_OPTIONS = [
    _option("clear-interior", "Clear Interior"),
    _option("occupied-interior", "Occupied Interior"),
    _option("confined-space", "Confined Space"),
    _option("off-hours", "Off Hours"),
    _option("protected-finish-zone", "Protected Finish Zone"),
]
ACCESS_ROOF_OPTIONS = [
    _option("roof-ladder", "Roof Ladder"),
    _option("scaffold-access", "Scaffold Access"),
    _option("mobile-lift", "Mobile Lift"),
    _option("rope-access", "Rope Access"),
    _option("crane-assisted", "Crane Assisted"),
]
ACCESS_SERVICE_OPTIONS = [
    _option("clear-access", "Clear Access"),
    _option("occupied-space", "Occupied Space"),
    _option("confined-space", "Confined Space"),
    _option("live-utility-zone", "Live Utility Zone"),
    _option("out-of-hours", "Out Of Hours"),
]
CHIMNEY_MATERIAL_OPTIONS = [
    _option("brick", "Brick"),
    _option("block", "Block"),
    _option("steel-liner", "Steel Liner"),
    _option("modular-system", "Modular System"),
]
WALL_MATERIAL_OPTIONS = [
    _option("brick", "Brick"),
    _option("aac-block", "AAC Block"),
    _option("concrete-block", "Concrete Block"),
    _option("reinforced-concrete", "Reinforced Concrete"),
]
DEMOLITION_SCOPE_OPTIONS = [
    _option("partition-wall", "Partition Wall"),
    _option("loadbearing-section", "Loadbearing Section"),
    _option("cladding-layer", "Cladding Layer"),
    _option("chimney-stack", "Chimney Stack"),
]
MASONRY_DAMAGE_OPTIONS = [
    _option("cracking", "Cracking"),
    _option("spalling", "Spalling"),
    _option("loose-joints", "Loose Joints"),
    _option("moisture-damage", "Moisture Damage"),
]
PLASTER_SYSTEM_OPTIONS = [
    _option("gypsum", "Gypsum"),
    _option("cement-lime", "Cement Lime"),
    _option("decorative-silicone", "Decorative Silicone"),
    _option("repair-mortar", "Repair Mortar"),
]
FACADE_SYSTEM_OPTIONS = [
    _option("etics-eps", "ETICS EPS"),
    _option("etics-mineral-wool", "ETICS Mineral Wool"),
    _option("rainscreen", "Rainscreen"),
    _option("fiber-cement", "Fiber Cement"),
]
INSULATION_MATERIAL_OPTIONS = [
    _option("eps", "EPS"),
    _option("mineral-wool", "Mineral Wool"),
    _option("pir-board", "PIR Board"),
    _option("xps", "XPS"),
]
FOUNDATION_SYSTEM_OPTIONS = [
    _option("strip-footing", "Strip Footing"),
    _option("raft-slab", "Raft Slab"),
    _option("pad-footing", "Pad Footing"),
    _option("pile-cap", "Pile Cap"),
]
PAVING_SYSTEM_OPTIONS = [
    _option("porcelain-pedestal", "Porcelain Pedestal"),
    _option("concrete-pedestal", "Concrete Pedestal"),
    _option("stone-pedestal", "Stone Pedestal"),
    _option("composite-pedestal", "Composite Pedestal"),
]
TILE_SYSTEM_OPTIONS = [
    _option("ceramic", "Ceramic"),
    _option("porcelain", "Porcelain"),
    _option("natural-stone", "Natural Stone"),
    _option("large-format", "Large Format"),
]
FLOOR_DAMAGE_OPTIONS = [
    _option("delamination", "Delamination"),
    _option("cracking", "Cracking"),
    _option("wear", "Wear"),
    _option("moisture-damage", "Moisture Damage"),
]
VINYL_SYSTEM_OPTIONS = [
    _option("lvt-click", "LVT Click"),
    _option("lvt-glue", "LVT Glue"),
    _option("spc", "SPC"),
    _option("sheet-vinyl", "Sheet Vinyl"),
]
WOOD_FLOOR_SYSTEM_OPTIONS = [
    _option("engineered-oak", "Engineered Oak"),
    _option("solid-oak", "Solid Oak"),
    _option("parquet", "Parquet"),
    _option("laminate", "Laminate"),
]
CONCRETE_FINISH_OPTIONS = [
    _option("screed", "Screed"),
    _option("self-leveling", "Self Leveling"),
    _option("power-float", "Power Float"),
    _option("polished-concrete", "Polished Concrete"),
]
ROOF_COVERING_OPTIONS = [
    _option("bitumen-membrane", "Bitumen Membrane"),
    _option("pvc-tpo", "PVC/TPO"),
    _option("metal-sheet", "Metal Sheet"),
    _option("clay-tile", "Clay Tile"),
]
ROOF_DAMAGE_OPTIONS = [
    _option("membrane-split", "Membrane Split"),
    _option("missing-covering", "Missing Covering"),
    _option("flashing-failure", "Flashing Failure"),
    _option("leak-trace", "Leak Trace"),
]
GUTTER_MATERIAL_OPTIONS = [
    _option("pvc", "PVC"),
    _option("painted-steel", "Painted Steel"),
    _option("aluminium", "Aluminium"),
    _option("titan-zinc", "Titan Zinc"),
]
GUTTER_FAILURE_OPTIONS = [
    _option("joint-leak", "Joint Leak"),
    _option("sagging-run", "Sagging Run"),
    _option("blockage", "Blockage"),
    _option("corrosion", "Corrosion"),
]
WINDOW_FRAME_OPTIONS = [
    _option("pvc", "PVC"),
    _option("wood", "Wood"),
    _option("aluminium", "Aluminium"),
    _option("alu-clad", "Alu Clad"),
]
WINDOW_DEFECT_OPTIONS = [
    _option("seal-failure", "Seal Failure"),
    _option("glazing-damage", "Glazing Damage"),
    _option("hardware-failure", "Hardware Failure"),
    _option("frame-deformation", "Frame Deformation"),
]
DOOR_SYSTEM_OPTIONS = [
    _option("interior-door", "Interior Door"),
    _option("exterior-door", "Exterior Door"),
    _option("fire-rated-door", "Fire Rated Door"),
    _option("security-door", "Security Door"),
]
DOOR_DEFECT_OPTIONS = [
    _option("leaf-damage", "Leaf Damage"),
    _option("frame-misalignment", "Frame Misalignment"),
    _option("lock-failure", "Lock Failure"),
    _option("weatherseal-failure", "Weatherseal Failure"),
]
ELECTRICAL_SYSTEM_OPTIONS = [
    _option("recessed-wiring", "Recessed Wiring"),
    _option("surface-trunking", "Surface Trunking"),
    _option("cable-tray", "Cable Tray"),
    _option("smart-home-bus", "Smart Home Bus"),
]
ELECTRICAL_FAULT_OPTIONS = [
    _option("short-circuit", "Short Circuit"),
    _option("socket-failure", "Socket Failure"),
    _option("switch-fault", "Switch Fault"),
    _option("circuit-overload", "Circuit Overload"),
]
PLUMBING_SYSTEM_OPTIONS = [
    _option("pex", "PEX"),
    _option("multilayer", "Multilayer"),
    _option("copper", "Copper"),
    _option("ppr", "PPR"),
]
PLUMBING_FAULT_OPTIONS = [
    _option("leak", "Leak"),
    _option("blockage", "Blockage"),
    _option("pressure-loss", "Pressure Loss"),
    _option("fixture-failure", "Fixture Failure"),
]
HEATING_SYSTEM_OPTIONS = [
    _option("radiator-system", "Radiator System"),
    _option("underfloor-system", "Underfloor System"),
    _option("heat-pump-hybrid", "Heat Pump Hybrid"),
    _option("boiler-loop", "Boiler Loop"),
]
BOILER_TYPE_OPTIONS = [
    _option("gas-condensing", "Gas Condensing"),
    _option("electric", "Electric"),
    _option("pellet", "Pellet"),
    _option("hybrid", "Hybrid"),
]
RADIATOR_TYPE_OPTIONS = [
    _option("panel", "Panel"),
    _option("column", "Column"),
    _option("designer", "Designer"),
    _option("towel-rail", "Towel Rail"),
]
PAINT_SYSTEM_OPTIONS = [
    _option("interior-emulsion", "Interior Emulsion"),
    _option("silicate", "Silicate"),
    _option("silicone", "Silicone"),
    _option("acrylic", "Acrylic"),
]
FINISHING_SCOPE_OPTIONS = [
    _option("skim-coat", "Skim Coat"),
    _option("decorative-plaster", "Decorative Plaster"),
    _option("trim-package", "Trim Package"),
    _option("wall-lining", "Wall Lining"),
]
DRYWALL_SYSTEM_OPTIONS = [
    _option("single-layer", "Single Layer"),
    _option("double-layer", "Double Layer"),
    _option("moisture-resistant", "Moisture Resistant"),
    _option("fire-resistant", "Fire Resistant"),
]
CEILING_SYSTEM_OPTIONS = [
    _option("gypsum-board", "Gypsum Board"),
    _option("mineral-grid", "Mineral Grid"),
    _option("metal-grid", "Metal Grid"),
    _option("stretch-ceiling", "Stretch Ceiling"),
]
TERRACE_SYSTEM_OPTIONS = [
    _option("timber-deck", "Timber Deck"),
    _option("composite-deck", "Composite Deck"),
    _option("pedestal-tile", "Pedestal Tile"),
    _option("concrete-slab", "Concrete Slab"),
]
FENCE_SYSTEM_OPTIONS = [
    _option("panel-fence", "Panel Fence"),
    _option("picket-fence", "Picket Fence"),
    _option("mesh-fence", "Mesh Fence"),
    _option("masonry-fence", "Masonry Fence"),
]
DRIVEWAY_SYSTEM_OPTIONS = [
    _option("concrete-block", "Concrete Block"),
    _option("asphalt", "Asphalt"),
    _option("resin-bound", "Resin Bound"),
    _option("poured-concrete", "Poured Concrete"),
]
LANDSCAPING_SCOPE_OPTIONS = [
    _option("lawn-establishment", "Lawn Establishment"),
    _option("planting-beds", "Planting Beds"),
    _option("grading", "Grading"),
    _option("irrigation-zone", "Irrigation Zone"),
]
INSPECTION_ASSET_OPTIONS = [
    _option("roof", "Roof"),
    _option("facade", "Facade"),
    _option("interior-finish", "Interior Finish"),
    _option("building-services", "Building Services"),
]
INSPECTION_TYPE_OPTIONS = [
    _option("routine", "Routine"),
    _option("warranty", "Warranty"),
    _option("handover", "Handover"),
    _option("emergency", "Emergency"),
]
CONDITION_BAND_OPTIONS = [
    _option("good", "Good"),
    _option("attention-needed", "Attention Needed"),
    _option("poor", "Poor"),
    _option("unsafe", "Unsafe"),
]
SERVICE_VISIT_OPTIONS = [
    _option("preventive", "Preventive"),
    _option("corrective", "Corrective"),
    _option("commissioning", "Commissioning"),
    _option("seasonal", "Seasonal"),
]
CLEANING_SURFACE_OPTIONS = [
    _option("glass-metal", "Glass And Metal"),
    _option("painted-surface", "Painted Surface"),
    _option("tile-stone", "Tile And Stone"),
    _option("mixed-interior", "Mixed Interior"),
]
CONTAMINATION_LEVEL_OPTIONS = [
    _option("light", "Light"),
    _option("standard", "Standard"),
    _option("heavy", "Heavy"),
    _option("hazardous", "Hazardous"),
]
EMERGENCY_SYSTEM_OPTIONS = [
    _option("roof-envelope", "Roof Envelope"),
    _option("electrical", "Electrical"),
    _option("plumbing", "Plumbing"),
    _option("heating", "Heating"),
]
EMERGENCY_INCIDENT_OPTIONS = [
    _option("water-ingress", "Water Ingress"),
    _option("power-failure", "Power Failure"),
    _option("pipe-burst", "Pipe Burst"),
    _option("heating-outage", "Heating Outage"),
]


def _parameter_row(
    wt_id: str,
    key: str,
    *,
    code: str,
    label: str,
    description: str,
    data_type: str,
    section: str,
    sort_order: int,
    unit: str | None = None,
    required: bool = False,
    min_number_value: float | int | None = None,
    max_number_value: float | int | None = None,
    vision_extractable: bool = False,
    manual_override_allowed: bool = True,
    default_text_value: str | None = None,
    default_number_value: float | int | None = None,
    default_boolean_value: bool | None = None,
    default_option_code: str | None = None,
    options: list[dict[str, str]] | None = None,
) -> dict[str, Any]:
    return {
        "_param_key": key,
        "_options": list(options or []),
        "id": f"wtp_{wt_id}_{key}",
        "work_type_id": f"wt_{wt_id}",
        "code": code,
        "slug": code,
        "name": label,
        "description": description,
        "data_type": data_type,
        "unit": unit,
        "section": section,
        "is_required": required,
        "sort_order": sort_order,
        "min_number_value": min_number_value,
        "max_number_value": max_number_value,
        "vision_extractable": vision_extractable,
        "manual_override_allowed": manual_override_allowed,
        "default_text_value": default_text_value,
        "default_number_value": default_number_value,
        "default_boolean_value": default_boolean_value,
        "default_option_code": default_option_code,
    }


def _number_param(
    wt_id: str,
    key: str,
    *,
    code: str,
    label: str,
    description: str,
    section: str,
    sort_order: int,
    unit: str,
    required: bool = False,
    min_number_value: float | int | None = None,
    max_number_value: float | int | None = None,
    vision_extractable: bool = False,
) -> dict[str, Any]:
    return _parameter_row(
        wt_id,
        key,
        code=code,
        label=label,
        description=description,
        data_type="number",
        section=section,
        sort_order=sort_order,
        unit=unit,
        required=required,
        min_number_value=min_number_value,
        max_number_value=max_number_value,
        vision_extractable=vision_extractable,
    )


def _text_param(
    wt_id: str,
    key: str,
    *,
    code: str,
    label: str,
    description: str,
    section: str,
    sort_order: int,
    required: bool = False,
) -> dict[str, Any]:
    return _parameter_row(
        wt_id,
        key,
        code=code,
        label=label,
        description=description,
        data_type="text",
        section=section,
        sort_order=sort_order,
        required=required,
    )


def _boolean_param(
    wt_id: str,
    key: str,
    *,
    code: str,
    label: str,
    description: str,
    section: str,
    sort_order: int,
    required: bool = False,
) -> dict[str, Any]:
    return _parameter_row(
        wt_id,
        key,
        code=code,
        label=label,
        description=description,
        data_type="boolean",
        section=section,
        sort_order=sort_order,
        required=required,
    )


def _option_param(
    wt_id: str,
    key: str,
    *,
    code: str,
    label: str,
    description: str,
    section: str,
    sort_order: int,
    options: list[dict[str, str]],
    required: bool = False,
    default_option_code: str | None = None,
    vision_extractable: bool = False,
) -> dict[str, Any]:
    return _parameter_row(
        wt_id,
        key,
        code=code,
        label=label,
        description=description,
        data_type="option",
        section=section,
        sort_order=sort_order,
        required=required,
        default_option_code=default_option_code,
        options=options,
        vision_extractable=vision_extractable,
    )


def _notes_param(wt_id: str, label: str, description: str) -> dict[str, Any]:
    return _text_param(
        wt_id,
        "notes",
        code="operator-notes",
        label=label,
        description=description,
        section="optional_notes",
        sort_order=80,
    )


def _severity_param(wt_id: str, *, description: str) -> dict[str, Any]:
    return _option_param(
        wt_id,
        "severity",
        code="severity-band",
        label="Severity Band",
        description=description,
        section="condition_or_damage",
        sort_order=50,
        options=SEVERITY_OPTIONS,
        required=True,
        vision_extractable=True,
    )


def _inspection_type_param(wt_id: str, *, default_option_code: str = "routine") -> dict[str, Any]:
    return _option_param(
        wt_id,
        "inspection_type",
        code="inspection-type",
        label="Inspection Type",
        description="Visit objective that determines report depth and response priority.",
        section="quantity_scope",
        sort_order=15,
        options=INSPECTION_TYPE_OPTIONS,
        required=True,
        default_option_code=default_option_code,
    )


def _area_repair_schema(
    wt_id: str,
    *,
    material_code: str,
    material_label: str,
    material_description: str,
    material_options: list[dict[str, str]],
    issue_code: str,
    issue_label: str,
    issue_description: str,
    issue_options: list[dict[str, str]],
    dimension_code: str,
    dimension_label: str,
    dimension_description: str,
    dimension_unit: str,
    dimension_min: float | int,
    dimension_max: float | int,
    access_options: list[dict[str, str]],
    area_label: str,
    notes_label: str,
) -> list[dict[str, Any]]:
    return [
        _number_param(
            wt_id,
            "area",
            code="work-area-sqm",
            label=area_label,
            description="Measured repair area used by pricing, vision reconciliation, and operator review.",
            section="quantity_scope",
            sort_order=10,
            unit="m2",
            required=True,
            min_number_value=0.1,
            max_number_value=25000,
            vision_extractable=True,
        ),
        _number_param(
            wt_id,
            "dimension",
            code=dimension_code,
            label=dimension_label,
            description=dimension_description,
            section="dimensions",
            sort_order=20,
            unit=dimension_unit,
            min_number_value=dimension_min,
            max_number_value=dimension_max,
            vision_extractable=True,
        ),
        _option_param(
            wt_id,
            "material",
            code=material_code,
            label=material_label,
            description=material_description,
            section="materials",
            sort_order=30,
            options=material_options,
            required=True,
            vision_extractable=True,
        ),
        _option_param(
            wt_id,
            "issue",
            code=issue_code,
            label=issue_label,
            description=issue_description,
            section="condition_or_damage",
            sort_order=40,
            options=issue_options,
            required=True,
            vision_extractable=True,
        ),
        _severity_param(
            wt_id,
            description="Operational severity used by pricing and triage for repair work.",
        ),
        _option_param(
            wt_id,
            "access",
            code="access-method",
            label="Access Method",
            description="Primary access method driving labor productivity and safety setup.",
            section="access_and_complexity",
            sort_order=60,
            options=access_options,
            required=True,
        ),
        _number_param(
            wt_id,
            "zones",
            code="repair-zones-count",
            label="Repair Zones",
            description="Number of distinct repair zones or local interventions within the work item.",
            section="quantity_scope",
            sort_order=70,
            unit="pcs",
            min_number_value=1,
            max_number_value=500,
            vision_extractable=True,
        ),
        _notes_param(
            wt_id,
            notes_label,
            "Free-form clarifications for manual review, pricing notes, or customer-visible remarks.",
        ),
    ]


def _area_installation_schema(
    wt_id: str,
    *,
    material_code: str,
    material_label: str,
    material_description: str,
    material_options: list[dict[str, str]],
    condition_code: str,
    condition_label: str,
    condition_description: str,
    condition_options: list[dict[str, str]],
    dimension_code: str,
    dimension_label: str,
    dimension_description: str,
    dimension_unit: str,
    dimension_max: float | int,
    access_options: list[dict[str, str]],
    area_label: str,
    zone_label: str,
    notes_label: str,
) -> list[dict[str, Any]]:
    return [
        _number_param(
            wt_id,
            "area",
            code="work-area-sqm",
            label=area_label,
            description="Measured installation area used as the main quantity driver.",
            section="quantity_scope",
            sort_order=10,
            unit="m2",
            required=True,
            min_number_value=0.1,
            max_number_value=40000,
            vision_extractable=True,
        ),
        _number_param(
            wt_id,
            "dimension",
            code=dimension_code,
            label=dimension_label,
            description=dimension_description,
            section="dimensions",
            sort_order=20,
            unit=dimension_unit,
            min_number_value=1,
            max_number_value=dimension_max,
        ),
        _option_param(
            wt_id,
            "material",
            code=material_code,
            label=material_label,
            description=material_description,
            section="materials",
            sort_order=30,
            options=material_options,
            required=True,
            vision_extractable=True,
        ),
        _option_param(
            wt_id,
            "condition",
            code=condition_code,
            label=condition_label,
            description=condition_description,
            section="condition_or_damage",
            sort_order=40,
            options=condition_options,
            required=True,
            vision_extractable=True,
        ),
        _option_param(
            wt_id,
            "access",
            code="access-method",
            label="Access Method",
            description="Primary site access arrangement affecting productivity and setup time.",
            section="access_and_complexity",
            sort_order=50,
            options=access_options,
            required=True,
        ),
        _number_param(
            wt_id,
            "zones",
            code="zone-count",
            label=zone_label,
            description="Number of rooms, elevations, bays, or work zones included in this item.",
            section="quantity_scope",
            sort_order=70,
            unit="pcs",
            min_number_value=1,
            max_number_value=500,
        ),
        _notes_param(
            wt_id,
            notes_label,
            "Free-form clarifications for sequencing, detailing, or operator review.",
        ),
    ]


def _count_installation_schema(
    wt_id: str,
    *,
    material_code: str,
    material_label: str,
    material_description: str,
    material_options: list[dict[str, str]],
    condition_code: str,
    condition_label: str,
    condition_description: str,
    condition_options: list[dict[str, str]],
    access_options: list[dict[str, str]],
    notes_label: str,
    quantity_label: str = "Quantity",
    width_label: str = "Opening Width",
    height_label: str = "Opening Height",
) -> list[dict[str, Any]]:
    return [
        _number_param(
            wt_id,
            "quantity",
            code="quantity",
            label=quantity_label,
            description="Count of units included in the work item.",
            section="quantity_scope",
            sort_order=10,
            unit="pcs",
            required=True,
            min_number_value=1,
            max_number_value=500,
            vision_extractable=True,
        ),
        _number_param(
            wt_id,
            "width",
            code="opening-width-mm",
            label=width_label,
            description="Typical opening or unit width used for sizing labor and material allowances.",
            section="dimensions",
            sort_order=20,
            unit="mm",
            min_number_value=300,
            max_number_value=4000,
        ),
        _number_param(
            wt_id,
            "height",
            code="opening-height-mm",
            label=height_label,
            description="Typical opening or unit height used for sizing labor and material allowances.",
            section="dimensions",
            sort_order=25,
            unit="mm",
            min_number_value=300,
            max_number_value=4000,
        ),
        _option_param(
            wt_id,
            "material",
            code=material_code,
            label=material_label,
            description=material_description,
            section="materials",
            sort_order=30,
            options=material_options,
            required=True,
            vision_extractable=True,
        ),
        _option_param(
            wt_id,
            "condition",
            code=condition_code,
            label=condition_label,
            description=condition_description,
            section="condition_or_damage",
            sort_order=40,
            options=condition_options,
            required=True,
        ),
        _option_param(
            wt_id,
            "access",
            code="access-method",
            label="Access Method",
            description="Primary access pattern affecting installation logistics and protection measures.",
            section="access_and_complexity",
            sort_order=50,
            options=access_options,
            required=True,
        ),
        _boolean_param(
            wt_id,
            "removal_required",
            code="existing-unit-removal-required",
            label="Existing Unit Removal Required",
            description="Whether the scope includes removal and disposal of existing units before installation.",
            section="quantity_scope",
            sort_order=70,
        ),
        _notes_param(
            wt_id,
            notes_label,
            "Free-form clarifications for detailing, delivery restrictions, or handover notes.",
        ),
    ]


def _count_repair_schema(
    wt_id: str,
    *,
    material_code: str,
    material_label: str,
    material_description: str,
    material_options: list[dict[str, str]],
    issue_code: str,
    issue_label: str,
    issue_description: str,
    issue_options: list[dict[str, str]],
    access_options: list[dict[str, str]],
    notes_label: str,
) -> list[dict[str, Any]]:
    return [
        _number_param(
            wt_id,
            "quantity",
            code="quantity",
            label="Quantity",
            description="Count of repair points, fixtures, or affected units.",
            section="quantity_scope",
            sort_order=10,
            unit="pcs",
            required=True,
            min_number_value=1,
            max_number_value=500,
            vision_extractable=True,
        ),
        _number_param(
            wt_id,
            "dimension",
            code="affected-size-mm",
            label="Affected Size",
            description="Typical damaged dimension used to estimate repair effort per unit.",
            section="dimensions",
            sort_order=20,
            unit="mm",
            min_number_value=1,
            max_number_value=5000,
        ),
        _option_param(
            wt_id,
            "material",
            code=material_code,
            label=material_label,
            description=material_description,
            section="materials",
            sort_order=30,
            options=material_options,
            required=True,
        ),
        _option_param(
            wt_id,
            "issue",
            code=issue_code,
            label=issue_label,
            description=issue_description,
            section="condition_or_damage",
            sort_order=40,
            options=issue_options,
            required=True,
        ),
        _severity_param(
            wt_id,
            description="Operational severity used to price the repair and prioritize dispatch.",
        ),
        _option_param(
            wt_id,
            "access",
            code="access-method",
            label="Access Method",
            description="Primary access arrangement for repair execution.",
            section="access_and_complexity",
            sort_order=60,
            options=access_options,
            required=True,
        ),
        _boolean_param(
            wt_id,
            "temporary_fix",
            code="temporary-fix-required",
            label="Temporary Fix Required",
            description="Whether a temporary stabilization or safe-state action is required before final repair.",
            section="quantity_scope",
            sort_order=70,
        ),
        _notes_param(
            wt_id,
            notes_label,
            "Free-form clarifications for diagnosis, follow-up, or operator commentary.",
        ),
    ]


def _length_installation_schema(
    wt_id: str,
    *,
    material_code: str,
    material_label: str,
    material_description: str,
    material_options: list[dict[str, str]],
    condition_code: str,
    condition_label: str,
    condition_description: str,
    condition_options: list[dict[str, str]],
    dimension_label: str,
    access_options: list[dict[str, str]],
    notes_label: str,
) -> list[dict[str, Any]]:
    return [
        _number_param(
            wt_id,
            "length",
            code="length-m",
            label="Length",
            description="Measured installed length used as the primary quantity driver.",
            section="quantity_scope",
            sort_order=10,
            unit="m",
            required=True,
            min_number_value=0.5,
            max_number_value=5000,
            vision_extractable=True,
        ),
        _number_param(
            wt_id,
            "dimension",
            code="section-size-mm",
            label=dimension_label,
            description="Nominal section size or width needed for takeoff and supplier selection.",
            section="dimensions",
            sort_order=20,
            unit="mm",
            min_number_value=50,
            max_number_value=1000,
        ),
        _option_param(
            wt_id,
            "material",
            code=material_code,
            label=material_label,
            description=material_description,
            section="materials",
            sort_order=30,
            options=material_options,
            required=True,
        ),
        _option_param(
            wt_id,
            "condition",
            code=condition_code,
            label=condition_label,
            description=condition_description,
            section="condition_or_damage",
            sort_order=40,
            options=condition_options,
            required=True,
        ),
        _option_param(
            wt_id,
            "access",
            code="access-method",
            label="Access Method",
            description="Primary access arrangement affecting installation setup and labor rate.",
            section="access_and_complexity",
            sort_order=50,
            options=access_options,
            required=True,
        ),
        _number_param(
            wt_id,
            "runs",
            code="run-count",
            label="Run Count",
            description="Number of distinct runs or fence/gutter sections in the work item.",
            section="quantity_scope",
            sort_order=70,
            unit="pcs",
            min_number_value=1,
            max_number_value=500,
        ),
        _notes_param(
            wt_id,
            notes_label,
            "Free-form clarifications for detailing, interfaces, or operator review.",
        ),
    ]


def _length_repair_schema(
    wt_id: str,
    *,
    material_code: str,
    material_label: str,
    material_description: str,
    material_options: list[dict[str, str]],
    issue_code: str,
    issue_label: str,
    issue_description: str,
    issue_options: list[dict[str, str]],
    access_options: list[dict[str, str]],
    notes_label: str,
) -> list[dict[str, Any]]:
    return [
        _number_param(
            wt_id,
            "length",
            code="length-m",
            label="Repair Length",
            description="Measured repair length used as the primary quantity driver.",
            section="quantity_scope",
            sort_order=10,
            unit="m",
            required=True,
            min_number_value=0.5,
            max_number_value=5000,
            vision_extractable=True,
        ),
        _number_param(
            wt_id,
            "dimension",
            code="section-size-mm",
            label="Section Size",
            description="Nominal gutter or linear element size relevant to repair takeoff.",
            section="dimensions",
            sort_order=20,
            unit="mm",
            min_number_value=50,
            max_number_value=1000,
        ),
        _option_param(
            wt_id,
            "material",
            code=material_code,
            label=material_label,
            description=material_description,
            section="materials",
            sort_order=30,
            options=material_options,
            required=True,
        ),
        _option_param(
            wt_id,
            "issue",
            code=issue_code,
            label=issue_label,
            description=issue_description,
            section="condition_or_damage",
            sort_order=40,
            options=issue_options,
            required=True,
            vision_extractable=True,
        ),
        _severity_param(
            wt_id,
            description="Operational severity used to prioritize gutter or linear repair work.",
        ),
        _option_param(
            wt_id,
            "access",
            code="access-method",
            label="Access Method",
            description="Primary access arrangement for repair execution.",
            section="access_and_complexity",
            sort_order=60,
            options=access_options,
            required=True,
        ),
        _number_param(
            wt_id,
            "joints",
            code="joint-count",
            label="Joint Count",
            description="Number of joints, outlets, or local repair points within the work item.",
            section="quantity_scope",
            sort_order=70,
            unit="pcs",
            min_number_value=1,
            max_number_value=500,
        ),
        _notes_param(
            wt_id,
            notes_label,
            "Free-form clarifications for leak tracing, localized failures, or operator commentary.",
        ),
    ]


def _volume_construction_schema(wt_id: str) -> list[dict[str, Any]]:
    return [
        _number_param(
            wt_id,
            "volume",
            code="volume-m3",
            label="Concrete Volume",
            description="Measured concrete or excavation volume used as the primary quantity driver.",
            section="quantity_scope",
            sort_order=10,
            unit="m3",
            required=True,
            min_number_value=0.1,
            max_number_value=10000,
        ),
        _number_param(
            wt_id,
            "depth",
            code="foundation-depth-mm",
            label="Foundation Depth",
            description="Design or measured excavation depth for structural takeoff and safety planning.",
            section="dimensions",
            sort_order=20,
            unit="mm",
            min_number_value=200,
            max_number_value=5000,
        ),
        _option_param(
            wt_id,
            "material",
            code="foundation-system-type",
            label="Foundation System Type",
            description="Structural foundation system that drives reinforcement, formwork, and concrete assumptions.",
            section="materials",
            sort_order=30,
            options=FOUNDATION_SYSTEM_OPTIONS,
            required=True,
        ),
        _option_param(
            wt_id,
            "condition",
            code="ground-condition",
            label="Ground Condition",
            description="Ground condition affecting excavation method, temporary works, and productivity.",
            section="condition_or_damage",
            sort_order=40,
            options=GROUND_CONDITION_OPTIONS,
            required=True,
        ),
        _option_param(
            wt_id,
            "access",
            code="site-access-method",
            label="Site Access Method",
            description="Primary access arrangement for excavation and concrete placement.",
            section="access_and_complexity",
            sort_order=50,
            options=ACCESS_EXTERIOR_OPTIONS,
            required=True,
        ),
        _number_param(
            wt_id,
            "zones",
            code="pour-zone-count",
            label="Pour Zones",
            description="Number of separate pours or foundation zones within the work item.",
            section="quantity_scope",
            sort_order=70,
            unit="pcs",
            min_number_value=1,
            max_number_value=100,
        ),
        _notes_param(
            wt_id,
            "Foundation Notes",
            "Free-form clarifications for reinforcement, sequencing, or site constraints.",
        ),
    ]


def _scope_installation_schema(
    wt_id: str,
    *,
    material_code: str,
    material_label: str,
    material_description: str,
    material_options: list[dict[str, str]],
    condition_options: list[dict[str, str]],
    dimension_code: str,
    dimension_label: str,
    dimension_description: str,
    dimension_unit: str,
    dimension_min: float | int,
    dimension_max: float | int,
    quantity_code: str,
    quantity_label: str,
    quantity_description: str,
    notes_label: str,
) -> list[dict[str, Any]]:
    return [
        _text_param(
            wt_id,
            "scope",
            code="scope-description",
            label="Scope Description",
            description="Structured summary of the installation scope used by API, operator review, and pricing.",
            section="quantity_scope",
            sort_order=10,
            required=True,
        ),
        _number_param(
            wt_id,
            "dimension",
            code=dimension_code,
            label=dimension_label,
            description=dimension_description,
            section="dimensions",
            sort_order=20,
            unit=dimension_unit,
            min_number_value=dimension_min,
            max_number_value=dimension_max,
        ),
        _option_param(
            wt_id,
            "material",
            code=material_code,
            label=material_label,
            description=material_description,
            section="materials",
            sort_order=30,
            options=material_options,
            required=True,
        ),
        _option_param(
            wt_id,
            "condition",
            code="site-condition",
            label="Existing Site Condition",
            description="Existing condition of the site or interface that affects installation productivity.",
            section="condition_or_damage",
            sort_order=40,
            options=condition_options,
            required=True,
        ),
        _option_param(
            wt_id,
            "access",
            code="access-method",
            label="Access Method",
            description="Primary access arrangement for installation crews and material delivery.",
            section="access_and_complexity",
            sort_order=50,
            options=ACCESS_SERVICE_OPTIONS,
            required=True,
        ),
        _number_param(
            wt_id,
            "quantity",
            code=quantity_code,
            label=quantity_label,
            description=quantity_description,
            section="quantity_scope",
            sort_order=70,
            unit="pcs",
            min_number_value=1,
            max_number_value=500,
        ),
        _notes_param(
            wt_id,
            notes_label,
            "Free-form clarifications for phasing, commissioning, or operator review.",
        ),
    ]


def _inspection_schema(wt_id: str) -> list[dict[str, Any]]:
    return [
        _number_param(
            wt_id,
            "quantity",
            code="quantity",
            label="Visit Count",
            description="Number of inspection visits covered by this work item.",
            section="quantity_scope",
            sort_order=10,
            unit="pcs",
            required=True,
            min_number_value=1,
            max_number_value=20,
        ),
        _inspection_type_param(wt_id),
        _number_param(
            wt_id,
            "dimension",
            code="inspection-area-sqm",
            label="Inspection Area",
            description="Approximate inspected area used for staffing and report planning.",
            section="dimensions",
            sort_order=20,
            unit="m2",
            min_number_value=1,
            max_number_value=50000,
        ),
        _option_param(
            wt_id,
            "material",
            code="asset-type",
            label="Asset Type",
            description="Primary inspected asset or subsystem.",
            section="materials",
            sort_order=30,
            options=INSPECTION_ASSET_OPTIONS,
            required=True,
        ),
        _option_param(
            wt_id,
            "condition",
            code="condition-band",
            label="Condition Band",
            description="Observed overall condition band communicated to the operator and pricing flows.",
            section="condition_or_damage",
            sort_order=40,
            options=CONDITION_BAND_OPTIONS,
            required=True,
        ),
        _option_param(
            wt_id,
            "access",
            code="access-method",
            label="Access Method",
            description="Primary access arrangement needed to complete the inspection safely.",
            section="access_and_complexity",
            sort_order=50,
            options=ACCESS_EXTERIOR_OPTIONS,
            required=True,
        ),
        _boolean_param(
            wt_id,
            "report_required",
            code="formal-report-required",
            label="Formal Report Required",
            description="Whether the visit requires a formal report package beyond checklist capture.",
            section="quantity_scope",
            sort_order=70,
        ),
        _notes_param(
            wt_id,
            "Inspection Notes",
            "Free-form clarifications for findings, exclusions, or follow-up actions.",
        ),
    ]


def _maintenance_schema(wt_id: str) -> list[dict[str, Any]]:
    return [
        _number_param(
            wt_id,
            "quantity",
            code="quantity",
            label="Visit Count",
            description="Number of maintenance visits covered by this item.",
            section="quantity_scope",
            sort_order=10,
            unit="pcs",
            required=True,
            min_number_value=1,
            max_number_value=50,
        ),
        _number_param(
            wt_id,
            "dimension",
            code="service-duration-hours",
            label="Service Duration",
            description="Expected duration per visit used for planning and dispatch.",
            section="dimensions",
            sort_order=20,
            unit="h",
            min_number_value=0.5,
            max_number_value=24,
        ),
        _option_param(
            wt_id,
            "material",
            code="service-asset-type",
            label="Service Asset Type",
            description="Asset or subsystem covered by the maintenance visit.",
            section="materials",
            sort_order=30,
            options=INSPECTION_ASSET_OPTIONS,
            required=True,
        ),
        _option_param(
            wt_id,
            "condition",
            code="service-visit-type",
            label="Service Visit Type",
            description="Type of maintenance action planned for the visit.",
            section="condition_or_damage",
            sort_order=40,
            options=SERVICE_VISIT_OPTIONS,
            required=True,
        ),
        _option_param(
            wt_id,
            "access",
            code="access-method",
            label="Access Method",
            description="Primary access arrangement for the maintenance visit.",
            section="access_and_complexity",
            sort_order=50,
            options=ACCESS_SERVICE_OPTIONS,
            required=True,
        ),
        _boolean_param(
            wt_id,
            "consumables",
            code="consumables-included",
            label="Consumables Included",
            description="Whether the visit includes consumables or replacement minor parts.",
            section="quantity_scope",
            sort_order=70,
        ),
        _notes_param(
            wt_id,
            "Maintenance Notes",
            "Free-form clarifications for visit scope, spare parts, or follow-up actions.",
        ),
    ]


def _cleaning_schema(wt_id: str) -> list[dict[str, Any]]:
    return [
        _number_param(
            wt_id,
            "area",
            code="work-area-sqm",
            label="Cleaning Area",
            description="Measured cleaned area used as the primary quantity driver.",
            section="quantity_scope",
            sort_order=10,
            unit="m2",
            required=True,
            min_number_value=1,
            max_number_value=50000,
            vision_extractable=True,
        ),
        _number_param(
            wt_id,
            "dimension",
            code="ceiling-height-mm",
            label="Ceiling Height",
            description="Typical room or working height that influences access equipment and productivity.",
            section="dimensions",
            sort_order=20,
            unit="mm",
            min_number_value=2200,
            max_number_value=8000,
        ),
        _option_param(
            wt_id,
            "material",
            code="surface-type",
            label="Surface Type",
            description="Dominant surface mix that determines chemistry and tooling.",
            section="materials",
            sort_order=30,
            options=CLEANING_SURFACE_OPTIONS,
            required=True,
        ),
        _option_param(
            wt_id,
            "condition",
            code="contamination-level",
            label="Contamination Level",
            description="Observed contamination level driving productivity, chemicals, and waste handling.",
            section="condition_or_damage",
            sort_order=40,
            options=CONTAMINATION_LEVEL_OPTIONS,
            required=True,
            vision_extractable=True,
        ),
        _option_param(
            wt_id,
            "access",
            code="access-method",
            label="Access Method",
            description="Primary access arrangement for cleaning crews and equipment.",
            section="access_and_complexity",
            sort_order=50,
            options=ACCESS_INTERIOR_OPTIONS,
            required=True,
        ),
        _number_param(
            wt_id,
            "bags",
            code="waste-bag-count",
            label="Waste Bag Count",
            description="Expected quantity of waste bags or disposal units produced by the cleaning scope.",
            section="quantity_scope",
            sort_order=70,
            unit="pcs",
            min_number_value=0,
            max_number_value=5000,
        ),
        _notes_param(
            wt_id,
            "Cleaning Notes",
            "Free-form clarifications for protection scope, hazardous residue, or handover remarks.",
        ),
    ]


def _emergency_schema(wt_id: str) -> list[dict[str, Any]]:
    return [
        _number_param(
            wt_id,
            "quantity",
            code="quantity",
            label="Incident Count",
            description="Number of incident locations or emergency interventions included in this item.",
            section="quantity_scope",
            sort_order=10,
            unit="pcs",
            required=True,
            min_number_value=1,
            max_number_value=50,
        ),
        _number_param(
            wt_id,
            "dimension",
            code="response-time-hours",
            label="Target Response Time",
            description="Target response time used for dispatching and emergency pricing logic.",
            section="dimensions",
            sort_order=20,
            unit="h",
            min_number_value=0.25,
            max_number_value=24,
        ),
        _option_param(
            wt_id,
            "material",
            code="affected-system",
            label="Affected System",
            description="Primary system or building element affected by the incident.",
            section="materials",
            sort_order=30,
            options=EMERGENCY_SYSTEM_OPTIONS,
            required=True,
        ),
        _option_param(
            wt_id,
            "condition",
            code="incident-type",
            label="Incident Type",
            description="Observed incident type driving emergency triage and stabilization logic.",
            section="condition_or_damage",
            sort_order=40,
            options=EMERGENCY_INCIDENT_OPTIONS,
            required=True,
        ),
        _severity_param(
            wt_id,
            description="Severity band used to escalate dispatch and price emergency response.",
        ),
        _option_param(
            wt_id,
            "access",
            code="access-method",
            label="Access Method",
            description="Primary access arrangement for emergency response crews.",
            section="access_and_complexity",
            sort_order=60,
            options=ACCESS_SERVICE_OPTIONS,
            required=True,
        ),
        _boolean_param(
            wt_id,
            "stabilization",
            code="temporary-stabilization-required",
            label="Temporary Stabilization Required",
            description="Whether immediate stabilization is required before the permanent repair scope.",
            section="quantity_scope",
            sort_order=70,
        ),
        _notes_param(
            wt_id,
            "Emergency Notes",
            "Free-form clarifications for dispatch, temporary works, or safety remarks.",
        ),
    ]


WORK_TYPE_PARAMETER_SCHEMAS: dict[str, list[dict[str, Any]]] = {
    "chimney_renovation": _area_repair_schema(
        "chimney_renovation",
        material_code="chimney-material-type",
        material_label="Chimney Material Type",
        material_description="Primary chimney build-up that defines compatible repair materials.",
        material_options=CHIMNEY_MATERIAL_OPTIONS,
        issue_code="masonry-damage-type",
        issue_label="Masonry Damage Type",
        issue_description="Observed masonry failure pattern driving the renovation scope.",
        issue_options=MASONRY_DAMAGE_OPTIONS,
        dimension_code="stack-height-mm",
        dimension_label="Stack Height",
        dimension_description="Approximate chimney stack height involved in the renovation scope.",
        dimension_unit="mm",
        dimension_min=500,
        dimension_max=15000,
        access_options=ACCESS_ROOF_OPTIONS,
        area_label="Renovation Area",
        notes_label="Chimney Renovation Notes",
    ),
    "chimney_new_build": _count_installation_schema(
        "chimney_new_build",
        material_code="chimney-system-type",
        material_label="Chimney System Type",
        material_description="Primary chimney construction system selected for the new build.",
        material_options=CHIMNEY_MATERIAL_OPTIONS,
        condition_code="opening-condition",
        condition_label="Structural Interface Condition",
        condition_description="Condition of slab and roof interfaces before chimney installation.",
        condition_options=SUBSTRATE_CONDITION_OPTIONS,
        access_options=ACCESS_ROOF_OPTIONS,
        notes_label="Chimney Build Notes",
        quantity_label="Chimney Count",
        width_label="Shaft Width",
        height_label="Shaft Height",
    ),
    "wall_construction": _area_installation_schema(
        "wall_construction",
        material_code="wall-material-type",
        material_label="Wall Material Type",
        material_description="Primary structural wall material used for the scope.",
        material_options=WALL_MATERIAL_OPTIONS,
        condition_code="substrate-condition",
        condition_label="Substrate Condition",
        condition_description="Condition of the supporting structure and interfaces before construction.",
        condition_options=SUBSTRATE_CONDITION_OPTIONS,
        dimension_code="wall-thickness-mm",
        dimension_label="Wall Thickness",
        dimension_description="Nominal wall thickness used for quantity takeoff and detailing.",
        dimension_unit="mm",
        dimension_max=500,
        access_options=ACCESS_INTERIOR_OPTIONS,
        area_label="Wall Area",
        zone_label="Wall Sections",
        notes_label="Wall Construction Notes",
    ),
    "wall_demolition": _area_repair_schema(
        "wall_demolition",
        material_code="demolition-scope-type",
        material_label="Demolition Scope Type",
        material_description="Primary wall or element type being demolished.",
        material_options=DEMOLITION_SCOPE_OPTIONS,
        issue_code="demolition-condition",
        issue_label="Existing Condition",
        issue_description="Existing wall condition affecting demolition method and waste handling.",
        issue_options=EXISTING_CONDITION_OPTIONS,
        dimension_code="wall-thickness-mm",
        dimension_label="Wall Thickness",
        dimension_description="Nominal wall thickness affecting demolition effort and waste volume.",
        dimension_unit="mm",
        dimension_min=50,
        dimension_max=600,
        access_options=ACCESS_INTERIOR_OPTIONS,
        area_label="Demolition Area",
        notes_label="Wall Demolition Notes",
    ),
    "plastering": _area_installation_schema(
        "plastering",
        material_code="plaster-system-type",
        material_label="Plaster System Type",
        material_description="Plaster system selected for the application scope.",
        material_options=PLASTER_SYSTEM_OPTIONS,
        condition_code="substrate-condition",
        condition_label="Substrate Condition",
        condition_description="Condition of the wall or ceiling substrate before plaster application.",
        condition_options=SUBSTRATE_CONDITION_OPTIONS,
        dimension_code="plaster-thickness-mm",
        dimension_label="Plaster Thickness",
        dimension_description="Target plaster thickness used for labor and material planning.",
        dimension_unit="mm",
        dimension_max=50,
        access_options=ACCESS_INTERIOR_OPTIONS,
        area_label="Plaster Area",
        zone_label="Room Count",
        notes_label="Plastering Notes",
    ),
    "facade_installation": _area_installation_schema(
        "facade_installation",
        material_code="facade-system-type",
        material_label="Facade System Type",
        material_description="Facade system selected for the installation scope.",
        material_options=FACADE_SYSTEM_OPTIONS,
        condition_code="substrate-condition",
        condition_label="Substrate Condition",
        condition_description="Condition of the substrate facade before new system installation.",
        condition_options=SUBSTRATE_CONDITION_OPTIONS,
        dimension_code="system-build-up-mm",
        dimension_label="Facade Build-Up",
        dimension_description="Total facade build-up thickness used for detailing and pricing.",
        dimension_unit="mm",
        dimension_max=400,
        access_options=ACCESS_EXTERIOR_OPTIONS,
        area_label="Facade Area",
        zone_label="Elevation Count",
        notes_label="Facade Installation Notes",
    ),
    "insulation_installation": _area_installation_schema(
        "insulation_installation",
        material_code="insulation-material-type",
        material_label="Insulation Material Type",
        material_description="Primary insulation material selected for the work item.",
        material_options=INSULATION_MATERIAL_OPTIONS,
        condition_code="substrate-condition",
        condition_label="Substrate Condition",
        condition_description="Condition of the receiving surface before insulation installation.",
        condition_options=SUBSTRATE_CONDITION_OPTIONS,
        dimension_code="insulation-thickness-mm",
        dimension_label="Insulation Thickness",
        dimension_description="Design insulation thickness used for takeoff and energy scope.",
        dimension_unit="mm",
        dimension_max=300,
        access_options=ACCESS_EXTERIOR_OPTIONS,
        area_label="Insulated Area",
        zone_label="Thermal Zones",
        notes_label="Insulation Notes",
    ),
    "foundation_work": _volume_construction_schema("foundation_work"),
    "pedestal_paving": _area_installation_schema(
        "pedestal_paving",
        material_code="paving-system-type",
        material_label="Paving System Type",
        material_description="Raised paving system selected for the terrace or deck.",
        material_options=PAVING_SYSTEM_OPTIONS,
        condition_code="substrate-condition",
        condition_label="Substrate Condition",
        condition_description="Condition of the base slab or terrace deck before paving installation.",
        condition_options=SUBSTRATE_CONDITION_OPTIONS,
        dimension_code="pedestal-height-mm",
        dimension_label="Pedestal Height",
        dimension_description="Typical pedestal adjustment height required by the scope.",
        dimension_unit="mm",
        dimension_max=500,
        access_options=ACCESS_EXTERIOR_OPTIONS,
        area_label="Paving Area",
        zone_label="Terrace Zones",
        notes_label="Pedestal Paving Notes",
    ),
    "tile_installation": _area_installation_schema(
        "tile_installation",
        material_code="tile-system-type",
        material_label="Tile System Type",
        material_description="Tile product family selected for installation.",
        material_options=TILE_SYSTEM_OPTIONS,
        condition_code="substrate-condition",
        condition_label="Substrate Condition",
        condition_description="Condition of the screed or wall substrate before tiling.",
        condition_options=SUBSTRATE_CONDITION_OPTIONS,
        dimension_code="tile-size-mm",
        dimension_label="Tile Size",
        dimension_description="Nominal tile edge dimension affecting productivity and layout.",
        dimension_unit="mm",
        dimension_max=1800,
        access_options=ACCESS_INTERIOR_OPTIONS,
        area_label="Tile Area",
        zone_label="Rooms",
        notes_label="Tile Installation Notes",
    ),
    "floor_renovation": _area_repair_schema(
        "floor_renovation",
        material_code="floor-finish-type",
        material_label="Floor Finish Type",
        material_description="Existing finish type that defines the repair method.",
        material_options=[
            _option("tile", "Tile"),
            _option("vinyl", "Vinyl"),
            _option("wood", "Wood"),
            _option("concrete", "Concrete"),
        ],
        issue_code="floor-damage-type",
        issue_label="Floor Damage Type",
        issue_description="Observed floor damage pattern driving the repair scope.",
        issue_options=FLOOR_DAMAGE_OPTIONS,
        dimension_code="repair-depth-mm",
        dimension_label="Repair Depth",
        dimension_description="Typical repair depth or local fill depth required by the scope.",
        dimension_unit="mm",
        dimension_min=1,
        dimension_max=150,
        access_options=ACCESS_INTERIOR_OPTIONS,
        area_label="Renovation Area",
        notes_label="Floor Renovation Notes",
    ),
    "vinyl_floor_installation": _area_installation_schema(
        "vinyl_floor_installation",
        material_code="vinyl-system-type",
        material_label="Vinyl System Type",
        material_description="Vinyl flooring system selected for installation.",
        material_options=VINYL_SYSTEM_OPTIONS,
        condition_code="substrate-condition",
        condition_label="Substrate Condition",
        condition_description="Condition of the subfloor before vinyl installation.",
        condition_options=SUBSTRATE_CONDITION_OPTIONS,
        dimension_code="wear-layer-microns",
        dimension_label="Wear Layer",
        dimension_description="Nominal wear layer thickness used for product selection.",
        dimension_unit="um",
        dimension_max=1000,
        access_options=ACCESS_INTERIOR_OPTIONS,
        area_label="Vinyl Area",
        zone_label="Rooms",
        notes_label="Vinyl Floor Notes",
    ),
    "wood_floor_installation": _area_installation_schema(
        "wood_floor_installation",
        material_code="wood-floor-system-type",
        material_label="Wood Floor System Type",
        material_description="Wood floor system selected for installation.",
        material_options=WOOD_FLOOR_SYSTEM_OPTIONS,
        condition_code="substrate-condition",
        condition_label="Substrate Condition",
        condition_description="Condition of the subfloor before wood floor installation.",
        condition_options=SUBSTRATE_CONDITION_OPTIONS,
        dimension_code="board-width-mm",
        dimension_label="Board Width",
        dimension_description="Typical board width affecting layout and productivity.",
        dimension_unit="mm",
        dimension_max=300,
        access_options=ACCESS_INTERIOR_OPTIONS,
        area_label="Wood Floor Area",
        zone_label="Rooms",
        notes_label="Wood Floor Notes",
    ),
    "concrete_floor": _area_installation_schema(
        "concrete_floor",
        material_code="concrete-finish-type",
        material_label="Concrete Finish Type",
        material_description="Concrete floor finish selected for the scope.",
        material_options=CONCRETE_FINISH_OPTIONS,
        condition_code="substrate-condition",
        condition_label="Substrate Condition",
        condition_description="Condition of the base before the floor build-up is placed.",
        condition_options=SUBSTRATE_CONDITION_OPTIONS,
        dimension_code="slab-thickness-mm",
        dimension_label="Slab Thickness",
        dimension_description="Target slab or screed thickness used for quantity takeoff.",
        dimension_unit="mm",
        dimension_max=250,
        access_options=ACCESS_INTERIOR_OPTIONS,
        area_label="Concrete Floor Area",
        zone_label="Pour Sections",
        notes_label="Concrete Floor Notes",
    ),
    "roof_repair": _area_repair_schema(
        "roof_repair",
        material_code="roof-covering-type",
        material_label="Roof Covering Type",
        material_description="Primary roof covering that defines compatible repair materials and labor method.",
        material_options=ROOF_COVERING_OPTIONS,
        issue_code="damage-type",
        issue_label="Damage Type",
        issue_description="Observed roof failure pattern driving the repair scope.",
        issue_options=ROOF_DAMAGE_OPTIONS,
        dimension_code="roof-pitch-deg",
        dimension_label="Roof Pitch",
        dimension_description="Typical roof pitch affecting safety setup and productivity.",
        dimension_unit="deg",
        dimension_min=0,
        dimension_max=75,
        access_options=ACCESS_ROOF_OPTIONS,
        area_label="Repair Area",
        notes_label="Roof Repair Notes",
    ),
    "roof_installation": _area_installation_schema(
        "roof_installation",
        material_code="roof-covering-type",
        material_label="Roof Covering Type",
        material_description="Primary roof covering system selected for installation.",
        material_options=ROOF_COVERING_OPTIONS,
        condition_code="deck-condition",
        condition_label="Roof Deck Condition",
        condition_description="Condition of the supporting deck or rafters before installation.",
        condition_options=SUBSTRATE_CONDITION_OPTIONS,
        dimension_code="roof-pitch-deg",
        dimension_label="Roof Pitch",
        dimension_description="Typical roof pitch affecting detailing and access strategy.",
        dimension_unit="deg",
        dimension_max=75,
        access_options=ACCESS_ROOF_OPTIONS,
        area_label="Roof Area",
        zone_label="Roof Planes",
        notes_label="Roof Installation Notes",
    ),
    "roof_inspection": _inspection_schema("roof_inspection"),
    "gutter_installation": _length_installation_schema(
        "gutter_installation",
        material_code="gutter-material-type",
        material_label="Gutter Material Type",
        material_description="Primary gutter system material selected for installation.",
        material_options=GUTTER_MATERIAL_OPTIONS,
        condition_code="fascia-condition",
        condition_label="Fascia Condition",
        condition_description="Condition of the fascia or support line before new gutter installation.",
        condition_options=SUBSTRATE_CONDITION_OPTIONS,
        dimension_label="Gutter Size",
        access_options=ACCESS_EXTERIOR_OPTIONS,
        notes_label="Gutter Installation Notes",
    ),
    "gutter_repair": _length_repair_schema(
        "gutter_repair",
        material_code="gutter-material-type",
        material_label="Gutter Material Type",
        material_description="Existing gutter material that defines repair details and accessories.",
        material_options=GUTTER_MATERIAL_OPTIONS,
        issue_code="gutter-failure-type",
        issue_label="Gutter Failure Type",
        issue_description="Observed gutter failure pattern driving the repair scope.",
        issue_options=GUTTER_FAILURE_OPTIONS,
        access_options=ACCESS_EXTERIOR_OPTIONS,
        notes_label="Gutter Repair Notes",
    ),
    "roof_insulation": _area_installation_schema(
        "roof_insulation",
        material_code="insulation-material-type",
        material_label="Insulation Material Type",
        material_description="Insulation material selected for the roof scope.",
        material_options=INSULATION_MATERIAL_OPTIONS,
        condition_code="roof-deck-condition",
        condition_label="Roof Deck Condition",
        condition_description="Condition of the roof deck before insulation installation.",
        condition_options=SUBSTRATE_CONDITION_OPTIONS,
        dimension_code="insulation-thickness-mm",
        dimension_label="Insulation Thickness",
        dimension_description="Design insulation thickness used for takeoff and detailing.",
        dimension_unit="mm",
        dimension_max=300,
        access_options=ACCESS_ROOF_OPTIONS,
        area_label="Insulated Roof Area",
        zone_label="Roof Zones",
        notes_label="Roof Insulation Notes",
    ),
    "window_installation": _count_installation_schema(
        "window_installation",
        material_code="window-frame-material",
        material_label="Window Frame Material",
        material_description="Primary frame material selected for installation.",
        material_options=WINDOW_FRAME_OPTIONS,
        condition_code="opening-condition",
        condition_label="Opening Condition",
        condition_description="Condition of the wall opening before the new window is installed.",
        condition_options=OPENING_CONDITION_OPTIONS,
        access_options=ACCESS_INTERIOR_OPTIONS,
        notes_label="Window Installation Notes",
        quantity_label="Window Count",
    ),
    "window_replacement": _count_repair_schema(
        "window_replacement",
        material_code="window-frame-material",
        material_label="Window Frame Material",
        material_description="Existing or replacement frame material that affects detailing.",
        material_options=WINDOW_FRAME_OPTIONS,
        issue_code="window-defect-type",
        issue_label="Window Defect Type",
        issue_description="Observed defect driving the replacement or remedial scope.",
        issue_options=WINDOW_DEFECT_OPTIONS,
        access_options=ACCESS_INTERIOR_OPTIONS,
        notes_label="Window Replacement Notes",
    ),
    "door_installation": _count_installation_schema(
        "door_installation",
        material_code="door-system-type",
        material_label="Door System Type",
        material_description="Door system selected for installation.",
        material_options=DOOR_SYSTEM_OPTIONS,
        condition_code="opening-condition",
        condition_label="Opening Condition",
        condition_description="Condition of the opening before door installation.",
        condition_options=OPENING_CONDITION_OPTIONS,
        access_options=ACCESS_INTERIOR_OPTIONS,
        notes_label="Door Installation Notes",
        quantity_label="Door Count",
    ),
    "door_repair": _count_repair_schema(
        "door_repair",
        material_code="door-system-type",
        material_label="Door System Type",
        material_description="Door type that defines compatible repair methods and parts.",
        material_options=DOOR_SYSTEM_OPTIONS,
        issue_code="door-defect-type",
        issue_label="Door Defect Type",
        issue_description="Observed defect driving the repair scope.",
        issue_options=DOOR_DEFECT_OPTIONS,
        access_options=ACCESS_INTERIOR_OPTIONS,
        notes_label="Door Repair Notes",
    ),
    "electrical_installation": _scope_installation_schema(
        "electrical_installation",
        material_code="electrical-system-type",
        material_label="Electrical System Type",
        material_description="Primary electrical installation system selected for the scope.",
        material_options=ELECTRICAL_SYSTEM_OPTIONS,
        condition_options=SUBSTRATE_CONDITION_OPTIONS,
        dimension_code="route-length-m",
        dimension_label="Route Length",
        dimension_description="Approximate cable route length for takeoff and labor planning.",
        dimension_unit="m",
        dimension_min=1,
        dimension_max=5000,
        quantity_code="circuit-count",
        quantity_label="Circuit Count",
        quantity_description="Number of circuits, runs, or controlled zones included in the scope.",
        notes_label="Electrical Installation Notes",
    ),
    "electrical_repair": _count_repair_schema(
        "electrical_repair",
        material_code="electrical-system-type",
        material_label="Electrical System Type",
        material_description="Affected electrical system family.",
        material_options=ELECTRICAL_SYSTEM_OPTIONS,
        issue_code="electrical-fault-type",
        issue_label="Electrical Fault Type",
        issue_description="Observed electrical fault driving the repair and safety response.",
        issue_options=ELECTRICAL_FAULT_OPTIONS,
        access_options=ACCESS_SERVICE_OPTIONS,
        notes_label="Electrical Repair Notes",
    ),
    "plumbing_installation": _scope_installation_schema(
        "plumbing_installation",
        material_code="plumbing-system-type",
        material_label="Plumbing System Type",
        material_description="Primary pipework or plumbing system selected for installation.",
        material_options=PLUMBING_SYSTEM_OPTIONS,
        condition_options=SUBSTRATE_CONDITION_OPTIONS,
        dimension_code="route-length-m",
        dimension_label="Route Length",
        dimension_description="Approximate pipe route length for takeoff and labor planning.",
        dimension_unit="m",
        dimension_min=1,
        dimension_max=5000,
        quantity_code="fixture-count",
        quantity_label="Fixture Count",
        quantity_description="Number of fixtures, drops, or outlets included in the scope.",
        notes_label="Plumbing Installation Notes",
    ),
    "plumbing_repair": _count_repair_schema(
        "plumbing_repair",
        material_code="plumbing-system-type",
        material_label="Plumbing System Type",
        material_description="Affected plumbing system family.",
        material_options=PLUMBING_SYSTEM_OPTIONS,
        issue_code="plumbing-fault-type",
        issue_label="Plumbing Fault Type",
        issue_description="Observed plumbing fault driving the repair scope.",
        issue_options=PLUMBING_FAULT_OPTIONS,
        access_options=ACCESS_SERVICE_OPTIONS,
        notes_label="Plumbing Repair Notes",
    ),
    "heating_installation": _scope_installation_schema(
        "heating_installation",
        material_code="heating-system-type",
        material_label="Heating System Type",
        material_description="Primary heating system configuration selected for installation.",
        material_options=HEATING_SYSTEM_OPTIONS,
        condition_options=SUBSTRATE_CONDITION_OPTIONS,
        dimension_code="heated-area-sqm",
        dimension_label="Heated Area",
        dimension_description="Approximate serviced floor area used for system sizing and pricing.",
        dimension_unit="m2",
        dimension_min=10,
        dimension_max=10000,
        quantity_code="heating-zone-count",
        quantity_label="Heating Zones",
        quantity_description="Number of zones or branches included in the installation scope.",
        notes_label="Heating Installation Notes",
    ),
    "boiler_installation": _count_installation_schema(
        "boiler_installation",
        material_code="boiler-type",
        material_label="Boiler Type",
        material_description="Boiler technology selected for installation.",
        material_options=BOILER_TYPE_OPTIONS,
        condition_code="plantroom-condition",
        condition_label="Plant Room Condition",
        condition_description="Condition of the plant room interfaces before boiler installation.",
        condition_options=SUBSTRATE_CONDITION_OPTIONS,
        access_options=ACCESS_SERVICE_OPTIONS,
        notes_label="Boiler Installation Notes",
        quantity_label="Boiler Count",
        width_label="Boiler Width",
        height_label="Boiler Height",
    ),
    "radiator_installation": _count_installation_schema(
        "radiator_installation",
        material_code="radiator-type",
        material_label="Radiator Type",
        material_description="Radiator type selected for installation.",
        material_options=RADIATOR_TYPE_OPTIONS,
        condition_code="wall-condition",
        condition_label="Wall Condition",
        condition_description="Condition of the supporting wall before installation.",
        condition_options=SUBSTRATE_CONDITION_OPTIONS,
        access_options=ACCESS_INTERIOR_OPTIONS,
        notes_label="Radiator Installation Notes",
        quantity_label="Radiator Count",
        width_label="Radiator Width",
        height_label="Radiator Height",
    ),
    "painting": _area_installation_schema(
        "painting",
        material_code="paint-system-type",
        material_label="Paint System Type",
        material_description="Paint system selected for the scope.",
        material_options=PAINT_SYSTEM_OPTIONS,
        condition_code="surface-condition",
        condition_label="Surface Condition",
        condition_description="Condition of the existing surface before painting.",
        condition_options=SUBSTRATE_CONDITION_OPTIONS,
        dimension_code="coat-count",
        dimension_label="Coat Count",
        dimension_description="Number of coats planned for the item.",
        dimension_unit="pcs",
        dimension_max=5,
        access_options=ACCESS_INTERIOR_OPTIONS,
        area_label="Paint Area",
        zone_label="Rooms",
        notes_label="Painting Notes",
    ),
    "interior_finishing": _area_installation_schema(
        "interior_finishing",
        material_code="finishing-scope-type",
        material_label="Finishing Scope Type",
        material_description="Primary finishing package selected for the scope.",
        material_options=FINISHING_SCOPE_OPTIONS,
        condition_code="substrate-condition",
        condition_label="Substrate Condition",
        condition_description="Condition of the substrate before interior finishing work.",
        condition_options=SUBSTRATE_CONDITION_OPTIONS,
        dimension_code="finish-thickness-mm",
        dimension_label="Finish Thickness",
        dimension_description="Typical finish build-up thickness used for detailing and pricing.",
        dimension_unit="mm",
        dimension_max=40,
        access_options=ACCESS_INTERIOR_OPTIONS,
        area_label="Finishing Area",
        zone_label="Rooms",
        notes_label="Interior Finishing Notes",
    ),
    "drywall_installation": _area_installation_schema(
        "drywall_installation",
        material_code="drywall-system-type",
        material_label="Drywall System Type",
        material_description="Drywall board system selected for installation.",
        material_options=DRYWALL_SYSTEM_OPTIONS,
        condition_code="frame-condition",
        condition_label="Frame Condition",
        condition_description="Condition of the supporting frame or substrate before board installation.",
        condition_options=SUBSTRATE_CONDITION_OPTIONS,
        dimension_code="board-thickness-mm",
        dimension_label="Board Thickness",
        dimension_description="Nominal board thickness used for detailing and takeoff.",
        dimension_unit="mm",
        dimension_max=25,
        access_options=ACCESS_INTERIOR_OPTIONS,
        area_label="Drywall Area",
        zone_label="Rooms",
        notes_label="Drywall Notes",
    ),
    "ceiling_installation": _area_installation_schema(
        "ceiling_installation",
        material_code="ceiling-system-type",
        material_label="Ceiling System Type",
        material_description="Ceiling system selected for installation.",
        material_options=CEILING_SYSTEM_OPTIONS,
        condition_code="plenum-condition",
        condition_label="Plenum Condition",
        condition_description="Condition of the plenum or support structure before ceiling installation.",
        condition_options=SUBSTRATE_CONDITION_OPTIONS,
        dimension_code="drop-height-mm",
        dimension_label="Drop Height",
        dimension_description="Typical ceiling drop height used for detailing and access planning.",
        dimension_unit="mm",
        dimension_max=2000,
        access_options=ACCESS_INTERIOR_OPTIONS,
        area_label="Ceiling Area",
        zone_label="Ceiling Zones",
        notes_label="Ceiling Notes",
    ),
    "terrace_construction": _area_installation_schema(
        "terrace_construction",
        material_code="terrace-system-type",
        material_label="Terrace System Type",
        material_description="Primary terrace build-up system selected for construction.",
        material_options=TERRACE_SYSTEM_OPTIONS,
        condition_code="base-condition",
        condition_label="Base Condition",
        condition_description="Condition of the supporting base before terrace construction.",
        condition_options=SUBSTRATE_CONDITION_OPTIONS,
        dimension_code="build-up-height-mm",
        dimension_label="Build-Up Height",
        dimension_description="Total terrace build-up height used for detailing and takeoff.",
        dimension_unit="mm",
        dimension_max=500,
        access_options=ACCESS_EXTERIOR_OPTIONS,
        area_label="Terrace Area",
        zone_label="Terrace Zones",
        notes_label="Terrace Construction Notes",
    ),
    "fence_installation": _length_installation_schema(
        "fence_installation",
        material_code="fence-system-type",
        material_label="Fence System Type",
        material_description="Primary fence system selected for installation.",
        material_options=FENCE_SYSTEM_OPTIONS,
        condition_code="ground-condition",
        condition_label="Ground Condition",
        condition_description="Ground condition affecting foundations and line setting.",
        condition_options=GROUND_CONDITION_OPTIONS,
        dimension_label="Fence Height",
        access_options=ACCESS_EXTERIOR_OPTIONS,
        notes_label="Fence Installation Notes",
    ),
    "driveway_paving": _area_installation_schema(
        "driveway_paving",
        material_code="driveway-surface-type",
        material_label="Driveway Surface Type",
        material_description="Primary driveway surface selected for the scope.",
        material_options=DRIVEWAY_SYSTEM_OPTIONS,
        condition_code="sub-base-condition",
        condition_label="Sub-Base Condition",
        condition_description="Condition of the existing sub-base before paving installation.",
        condition_options=SUBSTRATE_CONDITION_OPTIONS,
        dimension_code="paving-thickness-mm",
        dimension_label="Paving Thickness",
        dimension_description="Nominal paving or build-up thickness used for takeoff.",
        dimension_unit="mm",
        dimension_max=300,
        access_options=ACCESS_EXTERIOR_OPTIONS,
        area_label="Driveway Area",
        zone_label="Driveway Zones",
        notes_label="Driveway Paving Notes",
    ),
    "garden_landscaping": _area_installation_schema(
        "garden_landscaping",
        material_code="landscaping-scope-type",
        material_label="Landscaping Scope Type",
        material_description="Primary landscaping package selected for the scope.",
        material_options=LANDSCAPING_SCOPE_OPTIONS,
        condition_code="site-condition",
        condition_label="Site Condition",
        condition_description="Condition of the existing terrain before landscaping works.",
        condition_options=GROUND_CONDITION_OPTIONS,
        dimension_code="topsoil-depth-mm",
        dimension_label="Topsoil Depth",
        dimension_description="Typical topsoil or planting depth used for takeoff and logistics.",
        dimension_unit="mm",
        dimension_max=500,
        access_options=ACCESS_EXTERIOR_OPTIONS,
        area_label="Landscape Area",
        zone_label="Landscape Zones",
        notes_label="Landscaping Notes",
    ),
    "inspection": _inspection_schema("inspection"),
    "maintenance": _maintenance_schema("maintenance"),
    "cleaning_after_construction": _cleaning_schema("cleaning_after_construction"),
    "emergency_repair": _emergency_schema("emergency_repair"),
}


def build_parameter_catalog() -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    parameters: list[dict[str, Any]] = []
    parameter_options: list[dict[str, Any]] = []

    for wt_id, schema in WORK_TYPE_PARAMETER_SCHEMAS.items():
        for parameter in schema:
            param_key = parameter["_param_key"]
            option_defs = list(parameter["_options"])
            row = {key: value for key, value in parameter.items() if not key.startswith("_")}
            parameters.append(row)
            for index, option in enumerate(option_defs, start=1):
                parameter_options.append(
                    {
                        "id": f"wtpo_{wt_id}_{param_key}_{option['code'].replace('-', '_')}",
                        "work_type_parameter_id": row["id"],
                        "code": option["code"],
                        "label": option["label"],
                        "sort_order": index * 10,
                        "is_active": True,
                    }
                )

    return parameters, parameter_options
