[pytest]
addopts = -p no:cacheprovider
asyncio_mode = auto
filterwarnings =
    ignore:'asyncio\.iscoroutinefunction' is deprecated and slated for removal in Python 3\.16; use inspect\.iscoroutinefunction\(\) instead:DeprecationWarning:slowapi\.extension
